[package]
name = "rcdda"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.12.0"
features = ["nightly", "no-slow-safety-checks"]

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
